### ISSUE TITLE
handling no remote branch during gg sync 

### ISSUE THREAD

**Issue by thoiberg** [thoiberg/good-git#2]
Currently if you run a `gg sync` with a new branch that has no remote tracking set up you get:
```
Step 1 of 2: Integrating remote changes into local...
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> add-makefile
```

My suggestion is that `gg sync` should be set up to handle the event that no remote branch exists cleanly. 99.999999% of the time when I run a `git push` and get this:
```
fatal: The current branch add-makefile has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin add-makefile
```

I just copy that git push command and run it, so I think it's a good optimisation to completely automate that step.

 In terms of actions that means:

- Not failing on a `git pull` (or at least printing a warning)
- Automatically set up the git remote branch on push with the remote branch having the same name as the local one.

I'm envisioning something like:
```
$ gg sync
Step 1 of 2: Integrating remote changes into local...
WARNING: No remote branch set for <BRANCH_NAME>
Step 2 of 2: Step 2 of 2: Synchronising local changes to remote server...
Creating remote branch <BRANCH_NAME>
Step 2 of 2: Complete!
```

**Comment by brycehanscomb** [comment]
My thoughts, exactly, let's do it that way
